input_shape: [600,3]
    
weight_tie_pattern: [0,1,1,1]
  
num_freq_bands: 5           # number of freq bands, with original value (2 * K + 1)
max_freq: 20.               # maximum frequency, hyperparameter depending on how fine the data is
freq_base: 2              

num_latents: 16             # number of latents, or induced set points, or centroids. different papers giving it different names
latent_dim: 16             # latent dimension
  
cross_heads: 1              # number of heads for cross attention. paper said 1
cross_head_dim: 16          # number of dimensions per cross attention head
  
latent_heads: 4             # number of heads for latent self attention, 8
latent_head_dim: 16         # number of dimensions per latent self attention head
  
num_classes: 2              # output number of classes
attn_dropout: 0.
ff_dropout: 0.
fourier_encode_data: True   # whether to auto-fourier encode the data, using the input_axis given. defaults to True, but can be turned off if you are fourier encoding the data yourself
self_per_cross_attn: 2 